import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "./ucomponent/Footer"
import {ServiceContextProvider} from "../context/ServiceContext"
import { ProjectContextProvider } from "@/context/projectContext/ProjectContext";
import { BlogContextProvider } from "@/context/blogContext/BlogContext";
import { PageProvider } from "@/context/pageContext/PageContext";
import { NavbarProvider } from "@/context/pagesetting/NavbarContext";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
   <ServiceContextProvider>
      <ProjectContextProvider>
      <BlogContextProvider>
        <PageProvider>
          <NavbarProvider>
        {children}
        </NavbarProvider>
        </PageProvider>
        </BlogContextProvider>
      </ProjectContextProvider>
    </ServiceContextProvider>
        {/* {children} */}
        <Footer/>
      </body>
    </html>
  );
}
